const cotRows = [
  "S&P 500 Consolidated - CHICAGO MERCANTILE EXCHANGE",
  "GOLD - COMMODITY EXCHANGE INC.",
  "NASDAQ-100 Consolidated - CHICAGO MERCANTILE EXCHANGE",
  "MICRO E-MINI RUSSELL 2000 INDX - CHICAGO MERCANTILE EXCHANGE",
  "ULTRA UST BOND - CHICAGO BOARD OF TRADE",
  "JAPANESE YEN - CHICAGO MERCANTILE EXCHANGE",
]

const cotCols = {
  "% OF OI-Commercial-Long (All)": "percentOfOICommercialLongAll",
  "% OF OI-Noncommercial-Long (All)": "percentOfOINoncommercialLongAll",
  "% OF OI-Noncommercial-Short (All)": "percentOfOINoncommercialShortAll",
  "% OF Open Interest (OI) (All)": "percentOfOpenInterestAll",
  "As of Date in Form YYYY-MM-DD": "asOfDate",
  "CFTC Market Code in Initials": "cftcMarketCode",
  "Change in Open Interest (All)": "changeInOpenInterestAll",
  "Commercial Positions-Long (All)": "commercialPositionsLongAll",
  "Commercial Positions-Long (Old)": "commercialPositionsLongOld",
  "Commercial Positions-Short (All)": "commercialPositionsShortAll",
  "Commercial Positions-Short (Old)": "commercialPositionsShortOld",
  "Contract Units": "contractUnits",
  "Noncommercial Positions-Long (All)": "noncommercialPositionsLongAll",
  "Noncommercial Positions-Long (Old)": "noncommercialPositionsLongOld",
  "Noncommercial Positions-Short (All)": "noncommercialPositionsShortAll",
  "Noncommercial Positions-Short (Old)": "noncommercialPositionsShortOld",
  "Nonreportable Positions-Long (All)": "nonreportablePositionsLongAll",
  "Nonreportable Positions-Short (All)": "nonreportablePositionsShortAll",
  "Open Interest (All)": "openInterestAll",
  "Open Interest (Old)": "openInterestOld",
  "raders-Commercial-Short (All)": "tradersCommercialShortAll",
  "Total Reportable Positions-Long (All)": "totalReportablePositionsLongAll",
  "Total Reportable Positions-Long (Old)": "totalReportablePositionsLongOld",
  "Total Reportable Positions-Short (All)": "totalReportablePositionsShortAll",
  "Total Reportable Positions-Short (Old": "totalReportablePositionsShortOld",
  "Traders-Commercial-Long (All)": "tradersCommercialLongAll",
  "Traders-Noncommercial-Long (All)": "tradersNoncommercialLongAll",
  "Traders-Noncommercial-Short (All)": "tradersNoncommercialShortAll",
  "Traders-Total (All)": "tradersTotalAll",
  "Traders-Total (Old)": "tradersTotalOld"
};

const colFilter = [
  "As of Date in Form YYYY-MM-DD",
  "CFTC Market Code in Initials",
  "Open Interest (All)",
  "Noncommercial Positions-Long (All)",
  "Noncommercial Positions-Short (All)",
  "Noncommercial Positions-Long (Old)",
  "Noncommercial Positions-Short (Old)",
  "Commercial Positions-Long (All)",
  "Commercial Positions-Short (All)",
  "Commercial Positions-Long (Old)",
  "Commercial Positions-Short (Old)",
  "Total Reportable Positions-Long (All)",
  "Total Reportable Positions-Long (Old)",
  "Total Reportable Positions-Short (All)",
  "Total Reportable Positions-Short (Old",
  "Nonreportable Positions-Long (All)",
  "Nonreportable Positions-Short (All)",
  "Open Interest (Old)",
  "Change in Open Interest (All)",
  "% OF Open Interest (OI) (All)",
  "% OF OI-Noncommercial-Long (All)",
  "% OF OI-Noncommercial-Short (All)",
  "% OF OI-Commercial-Long (All)",
  "Contract Units",
  "Traders-Noncommercial-Long (All)",
  "Traders-Noncommercial-Short (All)",
  "Traders-Commercial-Long (All)",
  "raders-Commercial-Short (All)",
  "Traders-Total (All)",
  "Traders-Total (Old)"
];

const labels = [
  "asOfDate",
  "cftcMarketCode",
  "openInterestAll",
  "noncommercialPositionsLongAll",
  "noncommercialPositionsShortAll",
  "noncommercialPositionsLongOld",
  "noncommercialPositionsShortOld",
  "commercialPositionsLongAll",
  "commercialPositionsShortAll",
  "commercialPositionsLongOld",
  "commercialPositionsShortOld",
  "totalReportablePositionsLongAll",
  "totalReportablePositionsLongOld",
  "totalReportablePositionsShortAll",
  "totalReportablePositionsShortOld",
  "nonreportablePositionsLongAll",
  "nonreportablePositionsShortAll",
  "openInterestOld",
  "changeInOpenInterestAll",
  "percentOfOpenInterestAll",
  "percentOfOINoncommercialLongAll",
  "percentOfOINoncommercialShortAll",
  "percentOfOICommercialLongAll",
  "contractUnits",
  "tradersNoncommercialLongAll",
  "tradersNoncommercialShortAll",
  "tradersCommercialLongAll",
  "tradersCommercialShortAll",
  "tradersTotalAll",
  "tradersTotalOld"
];

module.exports = {
  cotCols
}